/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Query
         * @description Thin wrapper over `cdp.query.dispatch` -- the query layer is never
         *     reimplemented (`WEB_RESEARCH.md` §7.0/§7.2.1). Response shape varies by
         *     `kind` (each `QUERIES[kind]` returns its own dict), so there is
         *     deliberately no fixed `response_model` here -- same posture as
         *     `cdp query --json`, which prints this same raw dict.
         */
        get: operations["get_query_api_query_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace
         * @description `WEB_RESEARCH.md` §7.1's literal `/api/trace?from=&to=&max-hops=`
         *     surface, as a convenience alias over `/api/query` rather than a second
         *     dispatch path: `entry` maps to `kind=trace`, `frm`/`to` (without `entry`)
         *     maps to `kind=paths` -- the two query kinds the Atlas path-trace feature
         *     (`WEB_RESEARCH.md` §3, "this single feature is the demo") needs.
         */
        get: operations["get_trace_api_trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Sources
         * @description `dataflow.sources[]` listing -- there is no `kind=sources` in
         *     `cdp.query.QUERIES` (`trace`/`paths` consume sources internally via
         *     `_resolve_entry`, but nothing lists them for a picker). Same posture as
         *     `get_link`/`get_doctor`: read the artifact directly rather than invent
         *     a query-dispatch kind for a plain listing.
         */
        get: operations["get_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Source
         * @description Reads the repo working tree directly -- not the CDP store/index.db
         *     (`WEB_RESEARCH.md` §7.1: net-new capability, no other endpoint serves raw
         *     file bytes). `file` is attacker-controllable input from a browser, so
         *     this is a new trust boundary: containment is checked via `resolve()` +
         *     `is_relative_to()` *before* any file I/O, never via a caught exception
         *     after an attempted open. A 400 (not 403) is used for escapes, so the
         *     response doesn't distinguish "outside the root" from "doesn't exist" and
         *     can't be used to probe the filesystem.
         */
        get: operations["get_source_api_source_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_api_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/confidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Confidence */
        get: operations["get_confidence_api_confidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_api_node__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repos
         * @description Every state dir this machine's `cdp` registry knows about, with
         *     per-repo freshness (current git HEAD vs. the pinned snapshot's
         *     `as_of` commit). A registry entry whose state dir vanished, whose
         *     `index.db` is missing/locked, or whose git call fails gets its own
         *     `error` row instead of 500ing the whole list (mirrors `get_status`'s
         *     `StoreUnavailable`/`StoreLocked` -> per-request handling, just scoped
         *     to one row here instead of the whole response).
         *
         *     The registry only maps a repo's *git-remote identity* to a state dir
         *     (`cdp.store.registry.register`, called from `cmd_scan`) -- a repo
         *     scanned before that identity existed in the registry (e.g. this repo,
         *     whose origin was never `register`ed under its current remote) has no
         *     entry at all, even though `/api/status` resolves its state dir fine via
         *     the same `resolve_state_dir` fallback chain every other endpoint uses.
         *     Without this, `repos.repos[0]` (the frontend's single-repo assumption,
         *     `RepoHealthStrip.tsx`) would silently show whichever *other* repo
         *     happens to sort first in the registry. So: resolve the caller's actual
         *     `repo`/`state_dir` the normal way, and put that entry first -- matching
         *     an existing registry row by resolved state dir if one names the same
         *     directory, else synthesizing one so the current repo is never invisible
         *     or shadowed by an unrelated stale entry.
         */
        get: operations["get_repos_api_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Doctor
         * @description `<state>/doctor/*.json` is a plain filesystem directory
         *     (`cli.py:1858,1885`), not an `index.db` artifact -- no `ReadOnlyConnection`
         *     involved, no backend-polymorphism risk. 404 if the directory doesn't
         *     exist or has no reports yet (nobody has run `cdp doctor` here).
         */
        get: operations["get_doctor_api_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Link
         * @description Thin wrapper over the existing pure `link.query_service`
         *     (`cdp/link.py:217`) -- `link_edge` is a disposable, fully-replaced-on-scan
         *     table (`sqlite_backend.py:356`'s docstring), so no manifest-pinning
         *     concern here, just a plain read.
         */
        get: operations["get_link_api_link_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Links
         * @description All persisted link edges, unfiltered -- the constellation view's data
         *     source (`/api/link?service=` is a single-service lookup, not a listing).
         *     Same store/error handling as `/api/link` above.
         */
        get: operations["get_links_api_links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trajectory
         * @description `~/.cdp/trajectories.db` is a separate, cross-workspace, cumulative
         *     corpus (`cdp/trajectory.py` module docstring) -- not scoped to `repo=`/
         *     `state_dir=` the way every other endpoint above is.
         */
        get: operations["get_trajectory_api_trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Snapshots
         * @description This repo's scanned-commit history (`snapshot_meta`), oldest first --
         *     the time scrubber's timeline and the valid `/api/diff` `old`/`new`
         *     values.
         */
        get: operations["get_snapshots_api_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diff
         * @description Sha-mode only (`WEB_RESEARCH.md` §7.1's `/api/diff?old=&new=`) --
         *     dir-mode needs two arbitrary filesystem state directories, out of scope
         *     for a repo-scoped read endpoint. Delegates to the existing pure
         *     `diffs_mod.diff_snapshots` (`cdp/diffs.py:30`); the query-semantics
         *     invariant (§7.2.1) is preserved since that function is the same one
         *     `cmd_diff --old-sha/--new-sha` calls (`cli.py:2058-2107`).
         */
        get: operations["get_diff_api_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Run
         * @description Shells out to `cdp run` (`web/api/jobs.py`'s `spawn_or_join`) rather
         *     than calling `supervisor` in-process -- the subprocess inherits the real
         *     lock, `--resume`'s lease logic, and the repo-mismatch guard for free. A
         *     second POST while one is in flight for this `(repo, state_dir)` returns
         *     the same job's handle (`status="joined"`), not a second process.
         */
        post: operations["post_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Refresh */
        post: operations["post_refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Poll for a job's completion when there is no task table to watch --
         *     `POST /api/hookup/liveness`'s `cdp doctor` subprocess is the first such
         *     caller; `/api/run`/`/api/refresh` instead poll `/api/status`.
         */
        get: operations["get_job_api_job__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hookup/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hookup Preview
         * @description `WEB_RESEARCH.md` §4 item 1: "shows the exact files it will copy and
         *     the `--runner-cmd` it will wire" -- the file-list half, read-only.
         */
        get: operations["get_hookup_preview_api_hookup_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hookup/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Hookup Install
         * @description Shells out to `cdp install`, same posture as `/api/run`/`/api/refresh`
         *     (`register_leaf_agent`/`copy_distribution`, `cli.py:2754-2864`) -- but
         *     unlike those, a file copy is fast and idempotent, so this runs
         *     synchronously rather than through `jobs_mod.spawn_or_join`.
         */
        post: operations["post_hookup_install_api_hookup_install_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hookup/mcp-tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hookup Mcp Tools
         * @description The three `mcp_server` tools with a copy-to-clipboard client config
         *     (`WEB_RESEARCH.md` §4 item 1) -- read from `mcp_server/schemas.py`, never
         *     restated (§7.2's "client of the CLI's semantics, not a second
         *     implementation").
         */
        get: operations["get_hookup_mcp_tools_api_hookup_mcp_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hookup/liveness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Hookup Liveness
         * @description "Is it alive?" (`WEB_RESEARCH.md` §4 item 1): dispatches `cdp doctor`
         *     at one throwaway scope. Reuses `jobs_mod.spawn_or_join` (already generic
         *     over `kind`) so a second liveness POST while one is in flight joins
         *     rather than races it, same single-flight semantics as `/api/run`. Result
         *     is read back through the existing `GET /api/doctor` once the job
         *     (`GET /api/job/:id`) finishes.
         */
        post: operations["post_hookup_liveness_api_hookup_liveness_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClaimResponse */
        ClaimResponse: {
            /** Subject */
            subject: string;
            /** Kind */
            kind: string;
            /** Confidence */
            confidence: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
            /** Anchor Verified At */
            anchor_verified_at?: string | null;
            /** Claim Reviewed At */
            claim_reviewed_at?: string | null;
            /** Author Kind */
            author_kind?: string | null;
        };
        /**
         * ConfidenceResponse
         * @description `GET /api/confidence` -- one bulk `{raw graph id -> bucket}` map for a
         *     whole altitude, replacing the per-node `/api/node` fan-out the confidence
         *     lens used to do (353 requests at L2 after `ATLAS_REDESIGN.md` P0). Buckets
         *     are the `theme/confidence.ts` vocabulary: `high` / `medium` / `low` /
         *     `contested` / `unreviewed`.
         */
        ConfidenceResponse: {
            /** Level */
            level: string;
            /** Buckets */
            buckets: {
                [key: string]: unknown;
            };
        };
        /** CoverageResponse */
        CoverageResponse: {
            /** Fraction */
            fraction: number;
            /** Files Complete */
            files_complete: number;
            /** Files Total */
            files_total: number;
        };
        /** DataflowAnchorResponse */
        DataflowAnchorResponse: {
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Anchor */
            anchor?: string | null;
        };
        /** DataflowEdgeResponse */
        DataflowEdgeResponse: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Channel */
            channel: string;
            /** Confidence */
            confidence: string;
            /** Module */
            module?: string | null;
            anchor?: components["schemas"]["DataflowAnchorResponse"] | null;
        };
        /**
         * DiffResponse
         * @description `cdp.diffs.diff_snapshots`'s return value, passed through as-is
         *     (`WEB_RESEARCH.md` §7.1's `/api/diff` -- a typed structural delta, not a
         *     text diff). Left loose/`dict`-typed like `/api/query`'s response: the
         *     shape is `cdp/diffs.py`'s own, not re-modeled field-for-field here.
         */
        DiffResponse: {
            /** Old Sha */
            old_sha: string;
            /** New Sha */
            new_sha: string;
            /** Diff */
            diff: {
                [key: string]: unknown;
            };
        };
        /**
         * DoctorResponse
         * @description `GET /api/doctor` -- reads `<state>/doctor/*.json` straight off disk
         *     (`cdp/cli.py:1885`'s write side), no `index.db` involved. `models` keys on
         *     the model name each report was written under; `table` is
         *     `doctor.compatibility_table`'s same text rendering, included for parity
         *     with the CLI's own printed output when >1 model is present.
         */
        DoctorResponse: {
            /** Models */
            models: {
                [key: string]: unknown;
            };
            /** Table */
            table?: string | null;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /** File */
            file: string;
            /** Line */
            line: number;
            /** Anchor */
            anchor?: string | null;
        };
        /** FreshnessResponse */
        FreshnessResponse: {
            /** Live */
            live: number;
            /** Stale */
            stale: number;
            /** Unreviewed */
            unreviewed: number;
            /** Unknown Churn */
            unknown_churn: number;
        };
        /**
         * GraphEdgeResponse
         * @description `kind` carries the channel the edge was extracted from -- `call`,
         *     `persist`, `process_boundary`, `http_in`, `read`, `config_read`,
         *     `schema_own` at L2/L3 (`dataflow.edges[].channel`), `import` at L1, and
         *     the divergence signal `declared` / `observed` / `both` wherever the
         *     `graph` artifact is the source. `count` is how many underlying edges a
         *     rolled-up L3 edge stands for (always 1 at L2).
         */
        GraphEdgeResponse: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Kind */
            kind: string;
            /** Weight */
            weight?: number | null;
            /** Confidence */
            confidence?: string | null;
            /** Count */
            count?: number | null;
        };
        /**
         * GraphLegendEntry
         * @description One row of the canvas legend, computed from the same tables that drive
         *     the encoding so the legend can never drift from what is drawn.
         */
        GraphLegendEntry: {
            /** Type */
            type: string;
            /** Label */
            label: string;
            /** Family */
            family: string;
            /** Count */
            count: number;
        };
        /**
         * GraphNodeResponse
         * @description One node per package (L3) or typed `dataflow` node (L2). Fields that
         *     don't apply at a given level are left `None`/empty rather than the model
         *     forking in two.
         *
         *     `type`/`family`/`degree` are `ATLAS_REDESIGN.md` §3's visual-encoding
         *     channels, computed server-side so both canvases and the legend read the
         *     same source of truth. `node_id` is the *namespaced* (`web/api/nodeid.py`)
         *     form the inspector can hand straight to `/api/node/{id}` -- `None` for a
         *     synthetic L3 package super-node, which has no single underlying subject.
         *     `members` is only populated at L3 (the raw L2 ids rolled into this one).
         */
        GraphNodeResponse: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Level */
            level?: number | null;
            /** File Count */
            file_count?: number | null;
            /** By Role */
            by_role?: {
                [key: string]: unknown;
            } | null;
            /** By Language */
            by_language?: {
                [key: string]: unknown;
            } | null;
            /** Oversized */
            oversized?: boolean | null;
            /** Type */
            type?: string | null;
            /** Family */
            family?: string | null;
            /** Degree */
            degree?: number | null;
            /** Node Id */
            node_id?: string | null;
            /** Members */
            members?: string[] | null;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Level */
            level: string;
            /** Scope */
            scope?: string | null;
            /** Nodes */
            nodes: components["schemas"]["GraphNodeResponse"][];
            /** Edges */
            edges: components["schemas"]["GraphEdgeResponse"][];
            /**
             * Levels
             * @default []
             */
            levels: string[][];
            /**
             * Cycles
             * @default []
             */
            cycles: string[][];
            /** Divergence */
            divergence?: {
                [key: string]: unknown;
            } | null;
            /**
             * Legend
             * @default []
             */
            legend: components["schemas"]["GraphLegendEntry"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InstallPreviewResponse
         * @description `GET /api/hookup/preview` -- read-only description of what `cdp
         *     install --framework <framework> <target>` would do, without running it
         *     (`WEB_RESEARCH.md` §4 item 1: "shows the exact files it will copy").
         */
        InstallPreviewResponse: {
            /** Skill Dest */
            skill_dest: string;
            /** Skill Members */
            skill_members: string[];
            /** Leaf Agent File */
            leaf_agent_file?: string | null;
            /** Framework Note */
            framework_note?: string | null;
            /** Agents Md Path */
            agents_md_path: string;
            /** Agents Md Action */
            agents_md_action: string;
        };
        /**
         * InstallResultResponse
         * @description `POST /api/hookup/install` -- `cdp install` is a fast, idempotent
         *     file-copy, so unlike `/api/run`/`/api/refresh` this runs synchronously
         *     and returns the finished result rather than a `JobResponse` to poll.
         */
        InstallResultResponse: {
            /** Returncode */
            returncode: number;
            /** Stdout */
            stdout: string;
            /** Stderr */
            stderr: string;
        };
        /**
         * JobResponse
         * @description `POST /api/run`/`POST /api/refresh` (`WEB_RESEARCH.md` §7.2.4) --
         *     `status` is `"started"` for a freshly spawned subprocess or `"joined"`
         *     when a job for this `(repo, state_dir)` was already in flight and this
         *     call returned that same job's handle instead of racing a second process
         *     (single-flight, not a queue -- see `web/api/jobs.py`).
         */
        JobResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Pid */
            pid: number;
            /** Kind */
            kind: string;
        };
        /**
         * JobStatusResponse
         * @description `GET /api/job/:id` -- lets a caller that already holds a `job_id` (from
         *     a `JobResponse`) poll for completion without a task table to watch, which
         *     is what `/api/status`'s poll gives `/api/run`/`/api/refresh` but `POST
         *     /api/hookup/liveness`'s `cdp doctor` subprocess has none of.
         */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Repo */
            repo: string;
            /** State Dir */
            state_dir: string;
            /** Running */
            running: boolean;
            /** Returncode */
            returncode?: number | null;
        };
        /** LinkQueryResponse */
        LinkQueryResponse: {
            /** Service */
            service: string;
            /** Links */
            links: {
                [key: string]: unknown;
            }[];
            /** Unmatched */
            unmatched: {
                [key: string]: unknown;
            }[];
        };
        /**
         * LinksResponse
         * @description All persisted `link_edge` rows (`ReadOnlyConnection.read_link_edges`),
         *     unfiltered by service -- the constellation view's data source. Same
         *     loose `dict`-typed shape as `LinkQueryResponse` (straight from
         *     `link.scan_links`'s own output), split by `kind` ("link" vs
         *     "unmatched").
         */
        LinksResponse: {
            /** Links */
            links: {
                [key: string]: unknown;
            }[];
            /** Unmatched */
            unmatched: {
                [key: string]: unknown;
            }[];
        };
        /** McpToolResponse */
        McpToolResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Input Schema */
            input_schema: {
                [key: string]: unknown;
            };
        };
        /**
         * McpToolsResponse
         * @description `GET /api/hookup/mcp-tools` -- read straight from
         *     `mcp_server.schemas.TOOL_SCHEMAS`, never restated (§7.2's "client of the
         *     CLI's semantics, not a second implementation").
         */
        McpToolsResponse: {
            /** Tools */
            tools: components["schemas"]["McpToolResponse"][];
            /** Client Config */
            client_config: string;
        };
        /** NodeResponse */
        NodeResponse: {
            /** Node Id */
            node_id: string;
            /** Namespace */
            namespace: string;
            /** Claims */
            claims: components["schemas"]["ClaimResponse"][];
            /** Unknowns Count */
            unknowns_count: number;
            /** Edges In */
            edges_in: components["schemas"]["DataflowEdgeResponse"][];
            /** Edges Out */
            edges_out: components["schemas"]["DataflowEdgeResponse"][];
            scope?: components["schemas"]["ScopeSummaryResponse"] | null;
        };
        /**
         * RepoInfoResponse
         * @description One `cdp.store.registry` entry, per `GET /api/repos`. `head` is the
         *     *current* HEAD of the repo's working tree (`git rev-parse HEAD`, run at
         *     request time); `as_of_commit` is the commit the pinned snapshot's
         *     `inventory` was built against (same source `cdp.query._as_of` reads).
         *     `behind` is `0` when the two match, an exact `git rev-list --count`
         *     when cheaply derivable, or `None` (never a fabricated number) when the
         *     working tree moved, isn't a git repo, or the git call otherwise failed.
         *     `error` is set (and every other field but `repo_id`/`state_dir` left
         *     `None`) when this one registry entry couldn't be resolved at all --
         *     a broken entry never fails the whole list.
         */
        RepoInfoResponse: {
            /** Repo Id */
            repo_id: string;
            /** State Dir */
            state_dir: string;
            /** Repo Path */
            repo_path?: string | null;
            /** Head */
            head?: string | null;
            /** As Of Commit */
            as_of_commit?: string | null;
            /** Behind */
            behind?: number | null;
            /** Error */
            error?: string | null;
        };
        /** ReposResponse */
        ReposResponse: {
            /** Repos */
            repos: components["schemas"]["RepoInfoResponse"][];
        };
        /** ScopeSummaryResponse */
        ScopeSummaryResponse: {
            /** Node */
            node: string;
            /** Module */
            module: string;
            /** File Count */
            file_count: number;
            /** Loc */
            loc: number;
        };
        /** SnapshotMetaResponse */
        SnapshotMetaResponse: {
            /** Commit Sha */
            commit_sha: string;
            /** Created At */
            created_at: string;
        };
        /**
         * SnapshotsResponse
         * @description Ordered (oldest-first) list of this repo's scanned commits
         *     (`snapshot_meta`, via `ReadOnlyConnection.known_shas`/`snapshot_history`)
         *     -- the time scrubber's timeline, and the set of shas valid as `/api/diff`
         *     `old`/`new` params.
         */
        SnapshotsResponse: {
            /** Repo Id */
            repo_id: string;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotMetaResponse"][];
        };
        /** SourceEntryResponse */
        SourceEntryResponse: {
            /** Node */
            node: string;
            /** Channel */
            channel: string;
            /** Trigger */
            trigger: string;
            /** Module */
            module?: string | null;
            anchor?: components["schemas"]["DataflowAnchorResponse"] | null;
        };
        /**
         * SourceResponse
         * @description `GET /api/source` -- file bytes for the code-peek pane
         *     (`WEB_RESEARCH.md` §7.1, net-new: no other endpoint serves raw file
         *     content). `path` is the repo-relative POSIX string as requested (same
         *     format `cdp/inventory.py` stores in the `inventory` artifact, so it's
         *     consistent with what claims/anchors already reference).
         */
        SourceResponse: {
            /** Path */
            path: string;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Total Lines */
            total_lines: number;
            /** Lines */
            lines: string[];
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Count */
            count: number;
            /** Sources */
            sources: components["schemas"]["SourceEntryResponse"][];
        };
        /** StatusResponse */
        StatusResponse: {
            /** Run Id */
            run_id: string;
            /** Head */
            head?: string | null;
            coverage: components["schemas"]["CoverageResponse"];
            freshness?: components["schemas"]["FreshnessResponse"] | null;
            /** Waves */
            waves: components["schemas"]["WaveResponse"][];
            /** Tasks */
            tasks: components["schemas"]["TaskResponse"][];
        };
        /** TaskResponse */
        TaskResponse: {
            /** Node */
            node: string;
            /** State */
            state: string;
            /** Attempts */
            attempts: number;
            /** Last Error */
            last_error?: string | null;
        };
        /** TrajectoryResponse */
        TrajectoryResponse: {
            /** Shape */
            shape?: string | null;
            /** Runs */
            runs: components["schemas"]["TrajectoryRunResponse"][];
        };
        /** TrajectoryRunResponse */
        TrajectoryRunResponse: {
            /** Run Id */
            run_id: string;
            /** Node */
            node: string;
            /** Repo Id */
            repo_id: string;
            /** Model */
            model: string;
            /** Scope Shape */
            scope_shape: string;
            /** Tier */
            tier: string;
            /** Task Kind */
            task_kind: string;
            /** State */
            state?: string | null;
            /** Attempts */
            attempts?: number | null;
            /** Wall Ms */
            wall_ms?: number | null;
            /** Claims Emitted */
            claims_emitted?: number | null;
            /** Unknowns Emitted */
            unknowns_emitted?: number | null;
            /** Elision Regret */
            elision_regret?: number | null;
            /** Entailed */
            entailed?: number | null;
            /** Consistent */
            consistent?: number | null;
            /** Contradicted */
            contradicted?: number | null;
            /** Created At */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WaveNodeResponse */
        WaveNodeResponse: {
            /** Node */
            node: string;
            /** Status */
            status: string;
        };
        /** WaveResponse */
        WaveResponse: {
            /** Wave */
            wave: number;
            /** Level */
            level: number;
            /** Done */
            done: number;
            /** Total */
            total: number;
            /** File Count */
            file_count: number;
            /** Loc */
            loc: number;
            /** Nodes */
            nodes: components["schemas"]["WaveNodeResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_status_api_status_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_query_api_query_get: {
        parameters: {
            query: {
                /** @description one of cdp.query.QUERIES */
                kind: string;
                term?: string | null;
                budget?: number | null;
                claim_kind?: string | null;
                module?: string | null;
                subject?: string | null;
                from?: string | null;
                to?: string | null;
                "max-hops"?: number | null;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_api_trace_get: {
        parameters: {
            query?: {
                /** @description dataflow entry point */
                entry?: string | null;
                from?: string | null;
                to?: string | null;
                "max-hops"?: number | null;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_sources_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_source_get: {
        parameters: {
            query: {
                /** @description repo root to confine reads to */
                repo?: string;
                /** @description path, repo-relative POSIX string */
                file: string;
                /** @description 1-indexed line to center on */
                line?: number | null;
                /** @description lines of context around `line` (clamped) */
                ctx?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_graph_get: {
        parameters: {
            query: {
                /** @description altitude: L0 (symbols), L1 (files), L2 (typed dataflow nodes), L3 (packages) */
                level: string;
                /** @description filter to one package's/scope's neighborhood */
                scope?: string | null;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_confidence_api_confidence_get: {
        parameters: {
            query: {
                /** @description altitude, same vocabulary as /api/graph */
                level: string;
                /** @description same scope filter as /api/graph */
                scope?: string | null;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfidenceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_api_node__node_id__get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_repos_api_repos_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReposResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_doctor_api_doctor_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_link_api_link_get: {
        parameters: {
            query: {
                /** @description repo/service identifier to filter to */
                service: string;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_links_api_links_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trajectory_api_trajectory_get: {
        parameters: {
            query?: {
                /** @description exact scope_shape_key to filter to */
                shape?: string | null;
                /** @description max rows, newest first */
                budget?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrajectoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_snapshots_api_snapshots_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diff_api_diff_get: {
        parameters: {
            query: {
                old: string;
                new: string;
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_events_get: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
                /** @description defaults to the latest snapshot's manifest run_id */
                run_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_api_run_post: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
                /** @description wave-all | stale-only | scope:<node> | wave:<n> */
                target?: string;
                /** @description pass --resume through so a restarted job can rejoin */
                resume?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_refresh_api_refresh_post: {
        parameters: {
            query?: {
                /** @description repo path to resolve state for */
                repo?: string;
                state_dir?: string | null;
                /** @description cdp refresh --mode */
                mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_job__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hookup_preview_api_hookup_preview_get: {
        parameters: {
            query: {
                /** @description repository to install into */
                target: string;
                /** @description claude-code | langgraph | adk | none */
                framework?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_hookup_install_api_hookup_install_post: {
        parameters: {
            query: {
                /** @description repository to install into */
                target: string;
                /** @description claude-code | langgraph | adk | none */
                framework?: string;
                /** @description also install the PreToolUse nudge (claude-code only) */
                hook?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hookup_mcp_tools_api_hookup_mcp_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpToolsResponse"];
                };
            };
        };
    };
    post_hookup_liveness_api_hookup_liveness_post: {
        parameters: {
            query: {
                /** @description already-scanned repository to probe */
                target: string;
                state_dir?: string | null;
                /** @description cdp doctor --runner-cmd */
                runner_cmd: string;
                /** @description cdp doctor --model label */
                model: string;
                /** @description scope to probe; defaults to the cheapest one */
                node?: string | null;
                /** @description cdp doctor --timeout */
                timeout?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
