""".codescanner.toml -> Config. Every threshold, weight and severity lives here (rule 4)."""

from __future__ import annotations

import copy
import hashlib
import json
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

CONFIG_FILENAME = ".codescanner.toml"

DEFAULTS: dict[str, Any] = {
    "scan": {
        "max_file_bytes": 1_048_576,
        "binary_sniff_bytes": 8192,
        "detail": "threshold",
        "jobs": 0,
        "follow_symlinks": False,
    },
    "parse": {
        "degraded_error_ratio": 0.20,
    },
    "lines": {
        "docstring_as_comment": True,
    },
    "modules": {
        "enabled": True,
        "manifests": [
            "pom.xml", "build.gradle", "build.gradle.kts", "package.json",
            "go.mod", "Cargo.toml", "pyproject.toml", "setup.py",
            "*.csproj", "*.fsproj",
        ],
        "min_for_manifest_grouping": 2,
    },
    "roles": {
        "test": [],
        "generated": [],
        "vendored": [],
        "generated_markers": ["@Generated", "Code generated by", "DO NOT EDIT"],
        "generated_sniff_lines": 5,
        "stub_extensions": [".pyi", ".d.ts"],
    },
    "thresholds": {
        "long_function": 50,
        "deep_nesting": 4,
        "long_parameter_list": 5,
        "high_complexity": 10,
    },
    "score": {
        "include_roles": ["production"],
        "w_complexity": 25,
        "complexity_pct_knee": 0.15,
        "w_p95": 5,
        "p95_knee": "@thresholds.high_complexity",
        "p95_span": 20,
        "w_smells": 15,
        "smells_per_kloc_knee": 10,
        "w_docs": 10,
        "doc_target": 0.80,
        "security_cap": 60,
        "severity_weights": {"critical": 25, "high": 10, "medium": 3, "low": 0},
        "grades": {"A": 90, "B": 80, "C": 70, "D": 60},
        "rounding": "half_up",
        "empty_population": "null",
        "fail_on_empty": False,
    },
    "calibrate": {
        "enabled": True,
        "percentile": 0.95,
        "method": "nearest_rank",
        "min_population": 20,
    },
    "security": {
        "confidence_floor": "medium",
        "entropy_min_bits": 4.0,
        "entropy_min_chars": 20,
        "entropy_allowlist": ["uuid", "hex_digest", "base64_fixed"],
        "secret_name_pattern": "password|secret|api_key|token|private_key|credential",
        "suppress_marker": "scanner:ignore",
        "role_demotes_confidence": True,
        "severity": {
            "assignment_name.high": "high",
            "token_shape.high": "critical",
            "entropy.medium": "medium",
        },
        "dangerous_calls": {},
    },
    "packs": {
        "enabled": True,
    },
}


def _deep_merge(base: dict, override: dict) -> dict:
    result = copy.deepcopy(base)
    for key, value in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(value, dict):
            result[key] = _deep_merge(result[key], value)
        else:
            result[key] = value
    return result


def _resolve_references(node: Any, root: dict) -> Any:
    """Resolve '@a.b.c' string references against the resolved config tree (D8)."""
    if isinstance(node, str) and node.startswith("@") and "." in node:
        parts = node[1:].split(".")
        value: Any = root
        try:
            for part in parts:
                value = value[part]
        except (KeyError, TypeError):
            return node
        return value
    if isinstance(node, dict):
        return {k: _resolve_references(v, root) for k, v in node.items()}
    if isinstance(node, list):
        return [_resolve_references(v, root) for v in node]
    return node


def find_config_file(scan_root: Path) -> Path | None:
    """Scan root, then upward to the repo root (a directory containing .git). First match wins (R19)."""
    current = scan_root.resolve()
    seen_git = False
    while True:
        candidate = current / CONFIG_FILENAME
        if candidate.is_file():
            return candidate
        if (current / ".git").exists():
            seen_git = True
        if seen_git or current.parent == current:
            break
        current = current.parent
    return None


@dataclass(frozen=True)
class Config:
    resolved: dict[str, Any]
    source: str | None

    @property
    def digest(self) -> str:
        canonical = json.dumps(self.resolved, sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    def get(self, *path: str, default: Any = None) -> Any:
        node: Any = self.resolved
        for part in path:
            if not isinstance(node, dict) or part not in node:
                return default
            node = node[part]
        return node

    @classmethod
    def load(cls, scan_root: Path, explicit_path: Path | None = None) -> "Config":
        path = explicit_path if explicit_path is not None else find_config_file(scan_root)
        merged = copy.deepcopy(DEFAULTS)
        source: str | None = None
        if path is not None and path.is_file():
            with open(path, "rb") as f:
                user_config = tomllib.load(f)
            merged = _deep_merge(merged, user_config)
            source = str(path)
        resolved = _resolve_references(merged, merged)
        return cls(resolved=resolved, source=source)
